image = "/capstor/scratch/cscs/lukasd/images/ngc-jax+24.04-paxml.sqsh"

mounts = [
  "/capstor/scratch/cscs",
  "/capstor/scratch/cscs/dealmeih/nccl_plugin_todi/1.6.0-hcopy/libnccl-net.so:/usr/lib/libnccl-net-ofi.so",
  "/etc/slurm",
  #"/users/$USER/.ssh/cscs-key.pub:/users/$USER/.ssh/authorized_keys",
  #"/users/$USER/.vscode-server",
  #"/users/$USER/.wget-hsts"
]

writable = true

[annotations]
#com.hooks.dcgm.enabled = "true"
com.hooks.cxi.enabled = "true"

#[annotations]
#com.hooks.aws_ofi_nccl.enabled = "true"
#com.hooks.aws_ofi_nccl.variant = "cuda12"

[env]
#FI_CXI_DISABLE_HOST_REGISTER = "1"
#FI_MR_CACHE_MONITOR = "userfaultfd"
#
#TORCH_CPP_LOG_LEVEL = "INFO"
#TORCH_DISTRIBUTED_DEBUG = "DETAIL"
#TORCH_NCCL_BLOCKING_WAIT = "1"
#NCCL_ASYNC_ERROR_HANDLING = "1"
NCCL_DEBUG = "INFO"

CUDA_CACHE_DISABLE = "1"
NCCL_NET = "AWS Libfabric"
NCCL_CROSS_NIC = "1"
NCCL_NET_GDR_LEVEL = "PHB"
NCCL_NET_PLUGIN = "ofi"
FI_CXI_DISABLE_HOST_REGISTER = "1"
FI_MR_CACHE_MONITOR = "userfaultfd"
FI_CXI_DEFAULT_CQ_SIZE = "131072"
FI_CXI_DEFAULT_TX_SIZE = "32768"
FI_CXI_RX_MATCH_MODE = "software"

MPICH_NO_BUFFER_ALIAS_CHECK = "1"
MPICH_OFI_NIC_POLICY = "NUMA"
MPICH_OFI_STARTUP_CONNECT = "1"
MPICH_SMP_SINGLE_COPY_MODE = "NONE"
MPICH_GPU_SUPPORT_ENABLED = "0"
MPICH_OFI_CXI_COUNTER_REPORT = "2"
MPICH_COLL_OPT_OFF = "mpi_allgather"