#image = "/bret/scratch/cscs/lukasd/images/ngc-megatron+24.03.sqsh"
image = "/bret/scratch/cscs/lukasd/images/ngc-stable-diffusion+24.01.sqsh"

mounts = [
  "/bret:/bret",
  "/mchstor2:/mchstor2",
  "/etc/slurm:/etc/slurm",
  "/users/aurianer/.ssh/cscs-key.pub:/users/aurianer/.ssh/authorized_keys",
  "/users/aurianer/.bash_history:/users/aurianer/.bash_history"
]

writable = true

workdir = "/bret/scratch/cscs/aurianer/projects/mlcommons-training/stable_diffusion"

[annotations]
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "cuda12"

[env]
NCCL_DEBUG = "INFO"
FI_CXI_DISABLE_HOST_REGISTER = "1"
FI_MR_CACHE_MONITOR = "userfaultfd"
