image = "/bret/scratch/cscs/manitart/ce_images/ngc-recommendation_v2+24.03.sqsh"

mounts = [
  "/bret:/bret",
  "/mchstor2:/mchstor2",
  "/etc/slurm:/etc/slurm",

  # These are needed until the aws-ofi-nccl plugin is back in place
  "/usr/lib64/libnl-3.so:/usr/lib/libnl-3.so",
  "/usr/lib64/libnl-3.so.200:/usr/lib/libnl-3.so.200",
  "/usr/lib64/libnl-3.so.200.25.0:/usr/lib/libnl-3.so.200.25.0",
  "/bret/scratch/cscs/manitart/nccl_plugin_lib/libnccl-net.so:/usr/lib/libnccl-net-ofi.so"
]

writable = true

workdir = "/bret/scratch/cscs/manitart/mlcommons-training/recommendation_v2/torchrec_dlrm"

#[annotations]
#com.hooks.aws_ofi_nccl.enabled = "true"
#com.hooks.aws_ofi_nccl.variant = "cuda12"


[env]
#NCCL_DEBUG = "INFO"

# FIXME: These too are needed until the aws-ofi-nccl plugin is back in place
ENROOT_CXI_HOOK = "1"
NCCL_NET_PLUGIN = "ofi"

# FIXME: These two are probably needed so that NCCL does not hang
FI_CXI_DISABLE_HOST_REGISTER = "1"
FI_MR_CACHE_MONITOR = "userfaultfd"
