image = "/bret/scratch/cscs/lukasd/images/ngc-image_classification+24.03.sqsh"

mounts = [
  "/bret:/bret",
  "/mchstor2:/mchstor2",
  "/etc/slurm:/etc/slurm",
  "/users/lukasd/.ssh/cscs-key.pub:/users/lukasd/.ssh/authorized_keys",
  "/users/lukasd/.vscode-server:/users/lukasd/.vscode-server",
  "/users/lukasd/.wget-hsts:/users/lukasd/.wget-hsts"
]

writable = true

workdir = "/bret/scratch/cscs/lukasd/llm/training/image_classification"

[annotations]
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "cuda12"

[env]
NCCL_DEBUG = "INFO"
