#image = "/bret/scratch/cscs/lukasd/images/nvcr.io.nvidia.pytorch+24.03-py3.sqsh"
image = "/bret/scratch/cscs/lukasd/images/ngc-megatron+24.03.sqsh"

mounts = [
  "/bret:/bret",
  "/mchstor2:/mchstor2",
  "/etc/slurm:/etc/slurm",
  "/users/lukasd/.ssh/cscs-key.pub:/users/lukasd/.ssh/authorized_keys",
  "/users/lukasd/.vscode-server:/users/lukasd/.vscode-server",
  "/users/lukasd/.wget-hsts:/users/lukasd/.wget-hsts"
]

writable = true

workdir = "/bret/scratch/cscs/lukasd/llm/training/large_language_model/megatron-lm"

#[env]
#TORCH_CPP_LOG_LEVEL = "INFO"
#TORCH_DISTRIBUTED_DEBUG = "DETAIL"
#NCCL_DEBUG = "DEBUG"
#NCCL_ASYNC_ERROR_HANDLING = "1"

[annotations]
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "cuda12"

[env]
#NVIDIA_DISABLE_REQUIRE = "1"
#ENROOT_CXI_HOOK = "1"
#NCCL_NET_PLUGIN = "ofi"
NCCL_DEBUG = "INFO"
